name: SPU Bug Report Template
description: To report any SPU related bug
title: "[Bug]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of bug would you like to report?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
  - type: dropdown
    id: sub-area
    attributes:
      label: Modules Involved
      description: Which modules are involved in this issue?
      multiple: true
      options:
        - MPC protocol
        - SPU runtime
        - SPU compiler
        - PSI
        - PIR
        - Documentation/Tutorial/Example
        - Others
    validations:
      required: true
  - type: dropdown
    id: head
    attributes:
      label: Have you reproduced the bug with SPU HEAD?
      description: It is strongly suggested that you have reproduced the bug
        with latest SPU code
      options: ['Yes', 'No']
    validations:
      required: true
  - type: dropdown
    id: search
    attributes:
      label: Have you searched existing issues?
      description: To prevent duplicated reports, it is strongly suggested that you search existing issues first.
      options: ['Yes', 'No']
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SPU Version
      description: pip version if installed from package, commit id if build
        from source
      placeholder: e.g., spu 0.3.2b12
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      placeholder: e.g., Linux Ubuntu 16.04
    validations:
      required: true
  - type: input
    id: Python
    attributes:
      label: Python Version
      placeholder: e.g., 3.8
    validations:
      required: true
  - type: input
    id: Compiler
    attributes:
      label: Compiler Version
      description: if compiling from source
      placeholder: e.g., GCC 11.2.1
    validations:
      required: false
  
 
