name: SPU Bug Report Template
description: To report any SPU related bug
title: "[Bug]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of bug would you like to report?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
  - type: dropdown
    id: sub-area
    attributes:
      label: Modules Involved
      description: Which modules are involved in this issue?
      multiple: true
      options:
        - MPC protocol
        - SPU runtime
        - SPU compiler
        - PSI
        - PIR
        - Documentation/Tutorial/Example
        - Others
    validations:
      required: true
  - type: dropdown
    id: head
    attributes:
      label: Have you reproduced the bug with SPU HEAD?
      description: It is strongly suggested that you have reproduced the bug
        with latest SPU code
      options: ['Yes', 'No']
    validations:
      required: true
 
