name: SPU Issue Template
description: To report any SPU related bug
title: "[Bug]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of bug would you like to report?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
 