name: SPU Feature Request Template
description: To request a new feature
title: "[Feature]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of feature would you like to request?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
  - type: dropdown
    id: head
    attributes:
      label: Have you searched your request within existing issues?
      description: To prevent duplicated reports, it is strongly suggested that you search existing issues first.
      options: ['Yes', 'No']
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Current Behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
